# Safety Policy - Dependency Security Scanning
# Only use valid keywords supported by Safety CLI

security:
  # Minimum CVSS score to trigger alert (0-10)
  # 7+ = High/Critical vulnerabilities
  ignore-cvss-severity-below: 7.0
  
  # Fail on vulnerabilities with unknown severity
  ignore-cvss-unknown-severity: false
  
  # Continue build even if vulnerabilities found
  # Set to false for production (fail fast)
  continue-on-vulnerability-error: false
  
  # Ignore specific vulnerability IDs (use sparingly)
  ignore-vulnerabilities: []
    # Example: Add IDs here if needed
    # - 51668
  
  # Ignore unpinned requirements
  ignore-unpinned-requirements: false

